name: autodeployment with git-action

on:
  push:
    branches:
      - main

jobs:
  autodeploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: github repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17